### ISSUE TITLE
"SSLv3": method unknown or not provided by library

### ISSUE THREAD

**Issue by mwhesse** [leonjza/socat23#1]
I ran the build.sh script on ubuntu 18.04 and it seemed to work fine. But when testing the SSLv3 support I received the error message `"SSLv3": method unknown or not provided by library`

`$ /usr/local/bin/socat23 -v -x OPENSSL-LISTEN:4433,verify=0,method=SSLv3,... TCP:localhost:4080
socat23[19714] E openssl-method="SSLv3": method unknown or not provided by library`

Anything else that needs to be done / other than running build.sh to get the openssl SSLv3 support running in socat?

**Comment by leonjza** [comment]
Try `method=ssl3`.

**Comment by mwhesse** [comment]
This worked, thanks!
